version: '3.6'
services:
  plumber:
    build: .
    image: ${CCAO_REGISTRY_URL}/api-res-avm:latest
    privileged: true
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - api-res-avm-net
    environment:
      - AWS_S3_DVC_BUCKET
      - AWS_S3_MODEL_BUCKET
      - AWS_S3_MODEL_RUN_ID
      - AWS_S3_MODEL_YEAR
      - API_PORT
    secrets:
      - ENV_FILE
    restart: unless-stopped

networks:
  api_res_avm_net:
    ipam:
      config:
        - subnet: 211.25.0.0/16
    name: api-res-avm-net

secrets:
  ENV_FILE:
    file: secrets/ENV_FILE
